DISPLAY_WIDTH = 480
DISPLAY_HEIGHT = 320
DISPLAY_ROTATE = 1

SPI_PORT = 0
SPI_DEVICE = 0
SPI_SPEED = 16000000

GPIO_DC = 24
GPIO_RST = 25

IMU_ADDRESS = 0x68
IMU_SMOOTHING = 0.10

BOAT_NAME = "HERWA 23"
THEME = "premium_dark"

SCREEN_SWITCH_SECONDS = 8
LOG_PATH = "/home/sgson/BoatOS/logs/boatos.log"
